development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: findex_development
  username: mincong
  password: xlm1koxv
  #host: localhost
  #port: 5432

test: &test
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: findex_test
  username: mincong
  password: xlm1koxv

production:
  adapter: postgresql
  encoding: unicode
  database: findex_production
  pool: 5
  username: mincong
  password: xlm1koxv

cucumber:
  <<: *test

